microsoft/ADBench

ADBench/utils.py
otherwise it doesn't work with absolute paths UNIX paths
=> Only strip / from the end of the path

.gitignore, ADBench/run-all.ps1, CMakeLists.txt, CMakeSettings.json, etc/HunterGate.cmake
This PR fixes 2 problems:
1. CMake crashes in VS 2017/2019
2. Inconsistent output paths between generators - #19 https://github.com/awf/ADBench/issues/26#issuecomment-496293313
Solutions:
1. Update HunterGate (after that VS 2019 consistently works w/o errors on at least 2 machines, before it consistently crashed)
2. Set 
CMAKE_*_OUTPUT_DIRECTORY to 
generator expressions resolving to empty values in order 
to avoid creation of configuration related folders by multi-config generators such as `Visual Studio X X` https://cmake.org/cmake/help/v3.5/prop_tgt/RUNTIME_OUTPUT_DIRECTORY.html#prop_tgt:RUNTIME_OUTPUT_DIRECTORY
I also added CMakeSettings.json with sensible default config that puts CMakeCache into a folder nearby and makes x64-Release the default configuration for Visual Studio.
=> Fix build issues

CMakeLists.txt
The alternative is control flow in the script, but I think this is simpler.
=> Make all platforms use .exe extensions for executables, to help run-all.ps1

ADBench/run-all.ps1, tools/Finite/main.cpp, tools/Manual/main.cpp
Previously, the C++ implementations (at least some of them) would write output files with a different casing than expected by the run-all.ps1 script.  This doesn't matter on case-insensitive file systems, but it does matter on Linux.
I think it's a bit inconsistent that the casing of "manual" depends on whether we are using Eigen or not, but run-all.ps1 specifically lowercases the implementation name in these cases, so I guess it's intentional.
=> Use proper casing when writing timing files.

tools/Manual/main.cpp
This eliminates some warnings that otherwise clutter compilation output.
=> String literals are 'const char*', not 'char*', in C++.

CMakeLists.txt, src/cpp/runner/Benchmark.h, src/cpp/runner/main.cpp, test/cpp/modules/manual/CMakeLists.txt, test/cpp/runner/CMakeLists.txt, test/cpp/runner/CppRunnerTests.cpp, test/cpp/runner/MockGMM.cpp, test/cpp/runner/MockGMM.h
-Time always passes as duration<double> instead double. It helps to understand that time measures in seconds.
-Implemented a test which checks benchmark interrupt after exceeding the timelimit.
-Implemented a test which checks benchmark interrupt after exceeding the run limit. Moreover it checks that benchmarking loop is not optimized.
-Implemented a test which checks the function calculating repeats necessary for minimum measurement time archivement.
-Implemented a test which checks that time measured correctly.
=> Tests of corresponding methodology and c++ runner

src/cpp/runner/main.cpp, test/cpp/modules/manual/test_utils.h
I had to include `<cctype>` to get the C++ files to build.  I would be interested to learn how everyone else managed to build them without this include.  Is it perhaps a question of Visual C++ version?
=> Need to include <cctype> for std::toupper and std::isalnum

tools/Julia/common.jl
because the latter is deprecated.  See
https://github.com/JuliaMath/SpecialFunctions.jl/issues/154
Fixes https://github.com/awf/ADBench/issues/82
=> Use logabsgamma instead of lgamma

src/dotnet/utils/JacobianComparisonLib/JacobianComparison.cs
Patch implemented by @mikhailnikolaev
=> Use forward slashes in printed names instead of backslashes

ADBench/plot_graphs.py, ADBench/run-all.ps1
Fixes: https://github.com/awf/ADBench/issues/124
=> Use ASCII encoding for correctness files

ADBench/plot_graphs.py
Styles are hard linked to tools by map. For each new tool respected style must be added to the map. If tool style is not specified, default style will be used. Map has the following form:
```Python
all_styles = {
<tool name>: (<color>, <marker> [,<optional displaying name of the tool>]),
...
}
```
Using the same marks for the tools of the same language/platform is suggested.
=> Style mapping

ADBench/plot_graphs.py
Wrong Diffsharp module name in graph plotting script is fixed
=> Wrong diffsharp module name fixing

ADBench/plot_graphs.py
because of https://github.com/awf/ADBench/issues/143
Eventually we plan to change to a standard LSTM formulation
=> Special-case display of "LSTM" name

src/python/modules/Tensorflow/TensorflowHand.py
The code that produces a lot of warnings during differentiation is repaired
=> TF warning removing

src/cpp/runner/OutputSave.cpp
I don't know any reason why it would break things to add a new line, but having them improves the user experience of trying to view the files.
=> Add line ending after writing times and value

docs/python/Modules.md
Documentation about adding and testing Python modules is added.
**Note**: reference to global runner documentation from the file `/docs/python/Modules.md` is currently broken, because such a documentation is in the PR #153
=> Python module documentation

ADBench/AzureBatch/runallscript.sh, ADBench/AzureBatch/schedule.json, docs/AzureBatch.md
Azure Batch Job Schedule for weekly running all tools and creating graphs with storing them to the blob container, that can be observed by the [ADBench Web Viewer](https://github.com/awf/ADBench/pull/144), is created in [this](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/0f64a630-b912-4501-ad57-262a9e12637c/resourceGroups/ADBench/providers/Microsoft.Batch/batchAccounts/adbenchrunbatch/accountOverview) Azure Batch Account. This PR adds info about this job schedule.
Adding files:
1. Bash script that is run in a pool node.
2. JSON file that describes job schedule with missed blob container URL. It can be used for creating a new Azure Batch Job Schedule
3. Documentation that describes the script and the weekly run process and also contains instructions about …
=> Run all tool process in Azure Batch

ADBench/AzureBatch/runallscript.sh
**Note**: the new version of the script has already been added to the [Azure Batch](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/0f64a630-b912-4501-ad57-262a9e12637c/resourceGroups/ADBench/providers/Microsoft.Batch/batchAccounts/adbenchrunbatch/accountOverview)
=> Timeout for Azure Batch is doubled

ADBench/run-all.ps1
This PR is done due to some bug in the current array parameter sorting.
A `sort` alias for the comandlet `Sort-Object` was used in the PowerShell code. It works fine in Windows, but doesn't in Linux, because there is an utility called `sort` in Linux. That's why in _PowerShell Core_ there is no alias `sort` for `Sort-Object`, so calling `sort` the script uses Linux utility `sort`, that sorting values alphabetically by default. It leads to some strange behaviour, for example the script calculates GMM for `d = 10` before `d = 2`. So, now the alias using is removed.
=> Using Sort-Object

ADBench/run-all.ps1
Fixing problem when time file is creating without timeout value information in case of guaranteed timeout
=> Fixing wrong timeout file creation

ADBench/AzureBatch/runallscript.sh
1. Timeout is increased up to 900 seconds.
2. Additional tests for BA and Hand (now a numer of the tests is 10).
**Note**: the new version of the script has already been uploaded to the [Azure Batch](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/0f64a630-b912-4501-ad57-262a9e12637c/resourceGroups/ADBench/providers/Microsoft.Batch/batchAccounts/adbenchrunbatch/accountOverview)
=> Weekly run all process script changes

ADBench/plot_graphs.py
because the former is more precise
=> Say "timed out" instead of "terminated"

src/python/modules/PyTorch/gmm_objective.py
GMM objective for PyTorch is refactored with accelerating.
**Note**: plots for the tools other than `Tensorflow`, `Manual` and `PyTorch` can be wrong.
=> Accelerating PyTorch GMM objective

ADBench/plot_graphs.py
Now the script can use specified plot data file instead of the global runner output files.
This PR contains a part of changes from the closed PR #180. It is the fifth part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919
=> Using specified plot data file [part of #180]

ADBench/run-all.ps1, docs/GlobalRunner.md
The global runner takes additional parameter that defines maximum RAM size that the runner can consume. If test takes more, then it will be killed. Also, guaranteed out of memory checking is performed the same way as guaranteed timeout checking.
This PR solves the issue #172.
=> Checking out of memory

docs/BuildAndTest.md
As part of the install pip will currently changes the Python environment including replacing existing library versions without warning. If someone is using Conda environments, for example, this behaviour may be quite surprising.
=> Recommend venv

ADBench/CMakeLists.txt, src/python/CMakeLists.txt, test/python/CMakeLists.txt, tools/Autograd/CMakeLists.txt
When CMake is locating Python on Windows https://cmake.org/cmake/help/latest/module/FindPython3.html it defaults to searching the registry first. This is awkward behaviour on e.g. GitHub Actions where it has a later version of Python available but wouldn't be used if calling e.g. `python -V`.
I think it's closer to expectations to respect the environment variables instead where we want to use a precise version for benchmark comparability. That matches the current documentation which instructs put the binaries on the PATH:
https://github.com/microsoft/ADBench/blob/191c5244e7a815984d302ccbc48372137235a9dd/docs/BuildAndTest.md#prerequisites
=> Rely on environment variables to find Python

.github/workflows/main.yml
I've ported https://github.com/microsoft/ADBench/blob/9883bcdf06c27465ce7bd94ad4cff264a62f98ec/adobuilds/pr-win.yml over to GitHub Actions. That lets the build be more integrated rather than potentially calling into an external system (which is also not currently active).
There are a fair number of hard-coded values as before, we might want to look at extracting them to share with scripts but I'm keen to get a CI build active then expand to more of the benchmarks. This currently just does: `("Finite", "Manual", "PyTorch")`.
=> Get automated builds working again 

.github/workflows/main.yml, Dockerfile, docs/BuildAndTest.md, src/dotnet/modules/DiffSharpModule/DiffSharpModule.fsproj, src/dotnet/runner/DotnetRunner.csproj, test/dotnet/modules/DotnetModulesTests.csproj, test/dotnet/runner/DotnetRunnerTests/DotnetRunnerTests.csproj, test/dotnet/runner/DotnetRunnerTests/RunnerTests.cs, test/dotnet/runner/MockTest/MockTest.csproj, test/dotnet/utils/JacobianComparisonLibTests/JacobianComparisonLibTests.csproj
In order to update https://diffsharp.github.io/ to 1.0 we need a higher version of .NET Core, I've moved up to the next LTS version, 3.1. I'm putting this change in now as a good incremental step to match other tools.
=> Update the .NET Core module to target .NET Core 3.1

ADBench/azure-devops-ci.ps1, ADBench/requirements.txt, azure-devops.yml
Ensure a matplotlib compatible with plotly
Get a current .NET Core SDK for builds to match .NET projects.
Reduce time spent on dependencies
=> Devops build tidy

ADBench/plot_graphs.py
Without this, the script simply fails if the directories do not exist.
=> Create output directories if they do not exist.

src/cpp/runner/ModuleLoader.cpp
Remarkably it still worked before, but who knows what it did (and the compiler complained).
=> This should be a bitwise or, not a logical or.

CMakeLists.txt
This is related to #207 because macOS's default C++ compiler assumes it's still ten years ago.
=> Explicitly ask for C++14 support.

src/cpp/runner/ModuleLoader.cpp
I don't know the equivalent of `dlerror()` on Windows, but it shouldn't be difficult to support if someone does.
=> Print reason when dlopen fails.

src/cpp/modules/finite/finite.h
On my machine, the C++ code failed to build because of the missing include in this PR. Apparently, `std::numeric_limits` was indirectly included/defined in one of the other header files on older GCC versions; I'm running GCC 11.1.0.
=> Add missing include in finite.h
