microsoft/ADBench

_config.yml
index.md

Slight edits to the GH Pages landing page

gh-pages updates

---

tools/Julia/ba_Zygote.jl

This adds a version of the ba_* benchmark using Zygote instead of ForwardDiff.

Adding Zygote version of BA benchmark

---

CMakeLists.txt
test/modules/CMakeLists.txt
test/modules/cpp/manual/CMakeLists.txt
test/modules/cpp/manual/ManualGMMTests.cpp

Added GTest support to global CMakeLists
Also added GTest example

configured CMake and GTest

---

.vscode/extensions.json

- Added VScode config file, so on project open, VScode will recommend to install listed packages.

VScode integration with CMake

---

ADBench/azure-devops-ci.ps1
azure-devops.yml

Add Azure DevOps build definition for all the tools that we know work

 Add Azure DevOps build definition for all the tools that we know work 

---

src/cpp/modules/finite/FiniteBA.cpp
src/cpp/modules/finite/FiniteGMM.cpp
src/cpp/modules/finite/FiniteHand.cpp
src/cpp/modules/finite/FiniteLSTM.cpp
src/cpp/modules/finite/finite.h
src/cpp/modules/finiteEigen/FiniteEigenHand.cpp

- Made sure that the step in finite differences is comparable to the input variable
- Made sure that finite differences won't modify its input

Improved accuracy for finite differences.

---

ADBench/plot_graphs.py

Patch implemented by @mikhailnikolaev
Let's merge this one separately to simplify the other changes

Add --help option

---

ADBench/utils.py

instead of ad hoc splitting
Patch implemented by @mikhailnikolaev

Use os.path.split

---

src/julia/modules/Zygote/ZygoteBA.jl

Zygote is zygote in reverse mode
ZygoteF uses Zygote.forward_jacobian

Zygote BA uses reverse mode.

---

ADBench/plot_graphs.py

Adding styles for Julia and Autograd_split

Missed tool styles are added

---

ADBench/ADBenchWebViewer/ADBenchWebViewer.sln
ADBench/ADBenchWebViewer/ADBenchWebViewer/ADBenchWebViewer.csproj
ADBench/ADBenchWebViewer/ADBenchWebViewer/Controllers/AzureBlobHelper.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Controllers/IRunInfoProvider.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Controllers/PlotsController.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Models/PlotsInfo.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Models/RunInfo.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Program.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Startup.cs
ADBench/ADBenchWebViewer/ADBenchWebViewer/Views/Plots/GetPlotly.cshtml
ADBench/ADBenchWebViewer/ADBenchWebViewer/Views/Plots/GetStatic.cshtml
ADBench/ADBenchWebViewer/ADBenchWebViewer/Views/Plots/Index.cshtml
ADBench/ADBenchWebViewer/ADBenchWebViewer/appsettings.json

Web App for run result plot (static and plotly) viewing is implemented.
This application has been published on Azure. Its URL is https://adbenchwebviewer.azurewebsites.net
**Note**: in some web browsers (e.g. Google Chrome) plotly HTML pages are downloaded instead of displaying. That is because HTML pages stored in the blob container by Azure Batch have content type *octet-stream* and the property *type* of the tag **\<a\>** in web app response could be ignored be the browser.

ADBench web view application

---

docs/Docker.md
docs/python/Runner.md

Documentation for docker and python runner is added.

Python Runner & Docker documentation

---

data/gmm/gmm-data-gen.py

Implemeneted python script which generates data for gmm.

gmm data generator

---

ADBench/plot_graphs.py

This PR contains a part of changes from the closed PR #180. It is the first part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919

Separating graph drawing and value getting [part of #180]

---

ADBench/plot_graphs.py

Plot script now collects plot data and then uses it for creating graphs. Also, it saves plot data to the JSON file.
This PR contains a part of changes from the closed PR #180. It is the second part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919

Collecting plot data [part of #180]

---

ADBench/plot_graphs.py

This PR contains a part of changes from the closed PR #180. It is the third part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919

Move scanning files to the function [part of #180]

---

ADBench/plot_graphs.py

This PR contains a part of changes from the closed PR #180. It is the fourth part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919

IO paths creating refactoring [part of #180]

---

ADBench/plot_graphs.py

This PR contains a part of changes from the closed PR #180. It is the sixth part of the list, described here https://github.com/awf/ADBench/pull/180#issuecomment-569066919

Cosmetic changes [part of #180]

---

.vscode/extensions.json

Updated recommended extensions

---

.github/workflows/main.yml

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

Allow build to be manually triggered
